[2024-06-27T22:35:33.784+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:35:33.793+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [queued]>
[2024-06-27T22:35:33.796+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [queued]>
[2024-06-27T22:35:33.796+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:35:33.801+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 12:40:00+00:00
[2024-06-27T22:35:33.802+0000] {standard_task_runner.py:63} INFO - Started process 1378 to run task
[2024-06-27T22:35:33.803+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T12:40:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpd5axjx4l']
[2024-06-27T22:35:33.804+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask generate_and_insert_data
[2024-06-27T22:35:33.820+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:35:33.848+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T12:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T12:40:00+00:00'
[2024-06-27T22:35:33.848+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:35:33.882+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:35:33.882+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:35:33.883+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:35:33.887+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T12:40:00+00:00, execution_date=20230101T124000, start_date=20240627T223533, end_date=20240627T223533
[2024-06-27T22:35:33.903+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:35:33.910+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:35:33.910+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:16:59.695+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:16:59.705+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [queued]>
[2024-06-28T18:16:59.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [queued]>
[2024-06-28T18:16:59.707+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:16:59.712+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 12:40:00+00:00
[2024-06-28T18:16:59.713+0000] {standard_task_runner.py:63} INFO - Started process 2188 to run task
[2024-06-28T18:16:59.714+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T12:40:00+00:00', '--job-id', '155', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpps_dicoq']
[2024-06-28T18:16:59.715+0000] {standard_task_runner.py:91} INFO - Job 155: Subtask generate_and_insert_data
[2024-06-28T18:16:59.731+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:16:59.759+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T12:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T12:40:00+00:00'
[2024-06-28T18:16:59.760+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:16:59.816+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:16:59.817+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:16:59.817+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:16:59.817+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:16:59.817+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:16:59.822+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T12:40:00+00:00, execution_date=20230101T124000, start_date=20240628T181659, end_date=20240628T181659
[2024-06-28T18:16:59.862+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:16:59.869+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:16:59.870+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:38:59.353+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:38:59.363+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [queued]>
[2024-06-29T21:38:59.365+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [queued]>
[2024-06-29T21:38:59.365+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:38:59.370+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 12:40:00+00:00
[2024-06-29T21:38:59.372+0000] {standard_task_runner.py:63} INFO - Started process 1141 to run task
[2024-06-29T21:38:59.373+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T12:40:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpxfebu74r']
[2024-06-29T21:38:59.374+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask generate_and_insert_data
[2024-06-29T21:38:59.391+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:38:59.419+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T12:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T12:40:00+00:00'
[2024-06-29T21:38:59.419+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:38:59.476+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:38:59.476+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:38:59.476+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:38:59.476+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:38:59.476+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:38:59.481+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T12:40:00+00:00, execution_date=20230101T124000, start_date=20240629T213859, end_date=20240629T213859
[2024-06-29T21:38:59.520+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:38:59.527+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:38:59.528+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:02:48.504+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:02:48.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [queued]>
[2024-06-29T22:02:48.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [queued]>
[2024-06-29T22:02:48.517+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:02:48.521+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 12:40:00+00:00
[2024-06-29T22:02:48.523+0000] {standard_task_runner.py:63} INFO - Started process 1141 to run task
[2024-06-29T22:02:48.524+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T12:40:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpvw_0elmd']
[2024-06-29T22:02:48.525+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask generate_and_insert_data
[2024-06-29T22:02:48.542+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:40:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:02:48.570+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T12:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T12:40:00+00:00'
[2024-06-29T22:02:48.571+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:02:48.628+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:02:48.628+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:02:48.628+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:02:48.629+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:02:48.629+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:02:48.633+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T12:40:00+00:00, execution_date=20230101T124000, start_date=20240629T220248, end_date=20240629T220248
[2024-06-29T22:02:48.671+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:02:48.678+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:02:48.679+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
