[2024-06-27T22:34:14.743+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:34:14.752+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-27T22:34:14.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-27T22:34:14.755+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:34:14.759+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:40:00+00:00
[2024-06-27T22:34:14.761+0000] {standard_task_runner.py:63} INFO - Started process 768 to run task
[2024-06-27T22:34:14.762+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:40:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpzvkl10d1']
[2024-06-27T22:34:14.763+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask generate_and_insert_data
[2024-06-27T22:34:14.779+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:34:14.807+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:40:00+00:00'
[2024-06-27T22:34:14.807+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:34:14.841+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:34:14.841+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:34:14.842+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:34:14.847+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:40:00+00:00, execution_date=20230101T054000, start_date=20240627T223414, end_date=20240627T223414
[2024-06-27T22:34:14.861+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:34:14.867+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:34:14.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T22:53:19.817+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:53:19.827+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-27T22:53:19.829+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-27T22:53:19.829+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:53:19.833+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:40:00+00:00
[2024-06-27T22:53:19.835+0000] {standard_task_runner.py:63} INFO - Started process 939 to run task
[2024-06-27T22:53:19.836+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:40:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpcr65c_5z']
[2024-06-27T22:53:19.837+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask generate_and_insert_data
[2024-06-27T22:53:19.852+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [running]> on host a70edf9d8581
[2024-06-27T22:53:19.880+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:40:00+00:00'
[2024-06-27T22:53:19.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:53:19.915+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:53:19.915+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T22:53:19.915+0000] {logging_mixin.py:188} INFO - stderr: python3: can't open file '/opt/airflow/./generator/ecomm_generator.py': [Errno 2] No such file or directory
[2024-06-27T22:53:19.916+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:53:19.916+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:53:19.920+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:40:00+00:00, execution_date=20230101T054000, start_date=20240627T225319, end_date=20240627T225319
[2024-06-27T22:53:19.939+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:53:19.946+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:53:19.946+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:14:43.692+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:14:43.702+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-28T18:14:43.704+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-28T18:14:43.704+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:14:43.709+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:40:00+00:00
[2024-06-28T18:14:43.710+0000] {standard_task_runner.py:63} INFO - Started process 991 to run task
[2024-06-28T18:14:43.711+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:40:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpptt9tlr3']
[2024-06-28T18:14:43.712+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask generate_and_insert_data
[2024-06-28T18:14:43.729+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:14:43.757+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:40:00+00:00'
[2024-06-28T18:14:43.757+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:14:43.811+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:14:43.811+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:14:43.812+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:14:43.812+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:14:43.812+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:14:43.817+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:40:00+00:00, execution_date=20230101T054000, start_date=20240628T181443, end_date=20240628T181443
[2024-06-28T18:14:43.859+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:14:43.866+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:14:43.867+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:21:43.135+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:21:43.145+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-28T18:21:43.147+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-28T18:21:43.147+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:21:43.152+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:40:00+00:00
[2024-06-28T18:21:43.154+0000] {standard_task_runner.py:63} INFO - Started process 822 to run task
[2024-06-28T18:21:43.155+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:40:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpknnog709']
[2024-06-28T18:21:43.156+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask generate_and_insert_data
[2024-06-28T18:21:43.172+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [running]> on host 6570e5857071
[2024-06-28T18:21:43.200+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:40:00+00:00'
[2024-06-28T18:21:43.201+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:21:43.257+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:21:43.257+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:21:43.257+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:21:43.258+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:21:43.258+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:21:43.263+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:40:00+00:00, execution_date=20230101T054000, start_date=20240628T182143, end_date=20240628T182143
[2024-06-28T18:21:43.306+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:21:43.313+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:21:43.314+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:31:40.560+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:31:40.570+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-28T18:31:40.572+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-28T18:31:40.573+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:31:40.577+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:40:00+00:00
[2024-06-28T18:31:40.579+0000] {standard_task_runner.py:63} INFO - Started process 768 to run task
[2024-06-28T18:31:40.580+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:40:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpgkojxkd8']
[2024-06-28T18:31:40.581+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask generate_and_insert_data
[2024-06-28T18:31:40.597+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [running]> on host 50bf780463b8
[2024-06-28T18:31:40.627+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:40:00+00:00'
[2024-06-28T18:31:40.627+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:31:40.684+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:31:40.684+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:31:40.684+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:31:40.685+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:31:40.685+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:31:40.690+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:40:00+00:00, execution_date=20230101T054000, start_date=20240628T183140, end_date=20240628T183140
[2024-06-28T18:31:40.728+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:31:40.735+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:31:40.736+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:37:39.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:37:39.882+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-29T21:37:39.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-29T21:37:39.885+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:37:39.889+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:40:00+00:00
[2024-06-29T21:37:39.891+0000] {standard_task_runner.py:63} INFO - Started process 535 to run task
[2024-06-29T21:37:39.892+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:40:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp1x4wknqs']
[2024-06-29T21:37:39.892+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask generate_and_insert_data
[2024-06-29T21:37:39.909+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:37:39.937+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:40:00+00:00'
[2024-06-29T21:37:39.938+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:37:39.992+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:37:39.993+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:37:39.993+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:37:39.993+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:37:39.993+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:37:39.998+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:40:00+00:00, execution_date=20230101T054000, start_date=20240629T213739, end_date=20240629T213739
[2024-06-29T21:37:40.039+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:37:40.046+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:37:40.047+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:49:56.741+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:49:56.751+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-29T21:49:56.754+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-29T21:49:56.754+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:49:56.758+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:40:00+00:00
[2024-06-29T21:49:56.760+0000] {standard_task_runner.py:63} INFO - Started process 536 to run task
[2024-06-29T21:49:56.761+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:40:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp8_8evrew']
[2024-06-29T21:49:56.761+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask generate_and_insert_data
[2024-06-29T21:49:56.777+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [running]> on host 0b7af056b90c
[2024-06-29T21:49:56.805+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:40:00+00:00'
[2024-06-29T21:49:56.805+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:49:56.862+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:49:56.862+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:49:56.862+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:49:56.862+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:49:56.862+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:49:56.867+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:40:00+00:00, execution_date=20230101T054000, start_date=20240629T214956, end_date=20240629T214956
[2024-06-29T21:49:56.909+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:49:56.916+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:49:56.917+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:01:28.868+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:01:28.879+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-29T22:01:28.881+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [queued]>
[2024-06-29T22:01:28.881+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:01:28.885+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:40:00+00:00
[2024-06-29T22:01:28.887+0000] {standard_task_runner.py:63} INFO - Started process 535 to run task
[2024-06-29T22:01:28.888+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:40:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmps817n_6r']
[2024-06-29T22:01:28.889+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask generate_and_insert_data
[2024-06-29T22:01:28.905+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:40:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:01:28.933+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:40:00+00:00'
[2024-06-29T22:01:28.934+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:01:28.990+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:01:28.990+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:01:28.990+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:01:28.990+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:01:28.990+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:01:28.995+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:40:00+00:00, execution_date=20230101T054000, start_date=20240629T220128, end_date=20240629T220128
[2024-06-29T22:01:29.031+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:01:29.038+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:01:29.038+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
