[2024-06-27T22:35:58.889+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:35:58.899+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [queued]>
[2024-06-27T22:35:58.902+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [queued]>
[2024-06-27T22:35:58.902+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:35:58.906+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 14:50:00+00:00
[2024-06-27T22:35:58.908+0000] {standard_task_runner.py:63} INFO - Started process 1570 to run task
[2024-06-27T22:35:58.909+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T14:50:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpl1ise01_']
[2024-06-27T22:35:58.909+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask generate_and_insert_data
[2024-06-27T22:35:58.926+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:35:58.953+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T14:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T14:50:00+00:00'
[2024-06-27T22:35:58.953+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:35:58.987+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:35:58.987+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:35:58.987+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:35:58.991+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T14:50:00+00:00, execution_date=20230101T145000, start_date=20240627T223558, end_date=20240627T223558
[2024-06-27T22:35:59.011+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:35:59.017+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:35:59.017+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:17:40.823+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:17:40.833+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [queued]>
[2024-06-28T18:17:40.836+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [queued]>
[2024-06-28T18:17:40.836+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:17:40.840+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 14:50:00+00:00
[2024-06-28T18:17:40.842+0000] {standard_task_runner.py:63} INFO - Started process 2536 to run task
[2024-06-28T18:17:40.843+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T14:50:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpg0qzvayw']
[2024-06-28T18:17:40.844+0000] {standard_task_runner.py:91} INFO - Job 180: Subtask generate_and_insert_data
[2024-06-28T18:17:40.861+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:17:40.889+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T14:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T14:50:00+00:00'
[2024-06-28T18:17:40.889+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:17:40.946+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:17:40.946+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:17:40.947+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:17:40.947+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:17:40.947+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:17:40.952+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T14:50:00+00:00, execution_date=20230101T145000, start_date=20240628T181740, end_date=20240628T181740
[2024-06-28T18:17:40.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:17:40.993+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:17:40.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:39:24.665+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:39:24.675+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [queued]>
[2024-06-29T21:39:24.678+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [queued]>
[2024-06-29T21:39:24.678+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:39:24.682+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 14:50:00+00:00
[2024-06-29T21:39:24.684+0000] {standard_task_runner.py:63} INFO - Started process 1332 to run task
[2024-06-29T21:39:24.685+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T14:50:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpvxv1szte']
[2024-06-29T21:39:24.686+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask generate_and_insert_data
[2024-06-29T21:39:24.703+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:39:24.732+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T14:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T14:50:00+00:00'
[2024-06-29T21:39:24.732+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:39:24.788+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:39:24.788+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:39:24.788+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:39:24.789+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:39:24.789+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:39:24.794+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T14:50:00+00:00, execution_date=20230101T145000, start_date=20240629T213924, end_date=20240629T213924
[2024-06-29T21:39:24.832+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:39:24.839+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:39:24.840+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:03:12.847+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:03:12.858+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [queued]>
[2024-06-29T22:03:12.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [queued]>
[2024-06-29T22:03:12.862+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:03:12.867+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 14:50:00+00:00
[2024-06-29T22:03:12.869+0000] {standard_task_runner.py:63} INFO - Started process 1332 to run task
[2024-06-29T22:03:12.870+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T14:50:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp4ea4yoqm']
[2024-06-29T22:03:12.871+0000] {standard_task_runner.py:91} INFO - Job 91: Subtask generate_and_insert_data
[2024-06-29T22:03:12.889+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T14:50:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:03:12.922+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T14:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T14:50:00+00:00'
[2024-06-29T22:03:12.923+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:03:12.983+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:03:12.983+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:03:12.983+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:03:12.984+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:03:12.984+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:03:12.989+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T14:50:00+00:00, execution_date=20230101T145000, start_date=20240629T220312, end_date=20240629T220312
[2024-06-29T22:03:13.009+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:03:13.016+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:03:13.017+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
