[2024-06-27T22:35:30.031+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:35:30.041+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [queued]>
[2024-06-27T22:35:30.043+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [queued]>
[2024-06-27T22:35:30.044+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:35:30.048+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 12:20:00+00:00
[2024-06-27T22:35:30.049+0000] {standard_task_runner.py:63} INFO - Started process 1350 to run task
[2024-06-27T22:35:30.050+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T12:20:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpamyw5lka']
[2024-06-27T22:35:30.051+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask generate_and_insert_data
[2024-06-27T22:35:30.066+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:35:30.094+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T12:20:00+00:00'
[2024-06-27T22:35:30.095+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:35:30.127+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:35:30.127+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:35:30.127+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:35:30.132+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T12:20:00+00:00, execution_date=20230101T122000, start_date=20240627T223530, end_date=20240627T223530
[2024-06-27T22:35:30.152+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:35:30.159+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:35:30.159+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:16:53.984+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:16:53.994+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [queued]>
[2024-06-28T18:16:53.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [queued]>
[2024-06-28T18:16:53.997+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:16:54.001+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 12:20:00+00:00
[2024-06-28T18:16:54.003+0000] {standard_task_runner.py:63} INFO - Started process 2124 to run task
[2024-06-28T18:16:54.004+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T12:20:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpfv6t506f']
[2024-06-28T18:16:54.005+0000] {standard_task_runner.py:91} INFO - Job 151: Subtask generate_and_insert_data
[2024-06-28T18:16:54.022+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:16:54.051+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T12:20:00+00:00'
[2024-06-28T18:16:54.051+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:16:54.107+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:16:54.107+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:16:54.107+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:16:54.108+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:16:54.108+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:16:54.113+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T12:20:00+00:00, execution_date=20230101T122000, start_date=20240628T181653, end_date=20240628T181654
[2024-06-28T18:16:54.148+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:16:54.155+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:16:54.156+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:38:55.561+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:38:55.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [queued]>
[2024-06-29T21:38:55.574+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [queued]>
[2024-06-29T21:38:55.574+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:38:55.578+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 12:20:00+00:00
[2024-06-29T21:38:55.580+0000] {standard_task_runner.py:63} INFO - Started process 1113 to run task
[2024-06-29T21:38:55.581+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T12:20:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpdlhu66nz']
[2024-06-29T21:38:55.582+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask generate_and_insert_data
[2024-06-29T21:38:55.599+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:38:55.628+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T12:20:00+00:00'
[2024-06-29T21:38:55.628+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:38:55.683+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:38:55.683+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:38:55.684+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:38:55.684+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:38:55.684+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:38:55.689+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T12:20:00+00:00, execution_date=20230101T122000, start_date=20240629T213855, end_date=20240629T213855
[2024-06-29T21:38:55.724+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:38:55.730+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:38:55.730+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:02:44.611+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:02:44.621+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [queued]>
[2024-06-29T22:02:44.623+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [queued]>
[2024-06-29T22:02:44.623+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:02:44.628+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 12:20:00+00:00
[2024-06-29T22:02:44.630+0000] {standard_task_runner.py:63} INFO - Started process 1113 to run task
[2024-06-29T22:02:44.631+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T12:20:00+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpmn9pdp85']
[2024-06-29T22:02:44.632+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask generate_and_insert_data
[2024-06-29T22:02:44.649+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T12:20:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:02:44.677+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T12:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T12:20:00+00:00'
[2024-06-29T22:02:44.678+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:02:44.735+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:02:44.735+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:02:44.735+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:02:44.735+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:02:44.736+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:02:44.740+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T12:20:00+00:00, execution_date=20230101T122000, start_date=20240629T220244, end_date=20240629T220244
[2024-06-29T22:02:44.772+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:02:44.778+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:02:44.779+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
