[2024-06-27T22:36:25.142+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:36:25.152+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [queued]>
[2024-06-27T22:36:25.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [queued]>
[2024-06-27T22:36:25.154+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:36:25.159+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 17:10:00+00:00
[2024-06-27T22:36:25.160+0000] {standard_task_runner.py:63} INFO - Started process 1776 to run task
[2024-06-27T22:36:25.161+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T17:10:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpfxtjoa9h']
[2024-06-27T22:36:25.162+0000] {standard_task_runner.py:91} INFO - Job 122: Subtask generate_and_insert_data
[2024-06-27T22:36:25.178+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:36:25.206+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T17:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T17:10:00+00:00'
[2024-06-27T22:36:25.206+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:36:25.238+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:36:25.239+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:36:25.239+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:36:25.244+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T17:10:00+00:00, execution_date=20230101T171000, start_date=20240627T223625, end_date=20240627T223625
[2024-06-27T22:36:25.263+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:36:25.270+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:36:25.270+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:18:26.212+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:18:26.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [queued]>
[2024-06-28T18:18:26.226+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [queued]>
[2024-06-28T18:18:26.226+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:18:26.231+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 17:10:00+00:00
[2024-06-28T18:18:26.233+0000] {standard_task_runner.py:63} INFO - Started process 2924 to run task
[2024-06-28T18:18:26.234+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T17:10:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpmwo2nf1r']
[2024-06-28T18:18:26.234+0000] {standard_task_runner.py:91} INFO - Job 208: Subtask generate_and_insert_data
[2024-06-28T18:18:26.252+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:18:26.289+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T17:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T17:10:00+00:00'
[2024-06-28T18:18:26.290+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:18:26.349+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:18:26.349+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:18:26.349+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:18:26.350+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:18:26.350+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:18:26.355+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T17:10:00+00:00, execution_date=20230101T171000, start_date=20240628T181826, end_date=20240628T181826
[2024-06-28T18:18:26.390+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:18:26.397+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:18:26.398+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:39:51.518+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:39:51.528+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [queued]>
[2024-06-29T21:39:51.530+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [queued]>
[2024-06-29T21:39:51.531+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:39:51.535+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 17:10:00+00:00
[2024-06-29T21:39:51.537+0000] {standard_task_runner.py:63} INFO - Started process 1537 to run task
[2024-06-29T21:39:51.538+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T17:10:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpuqw32b3b']
[2024-06-29T21:39:51.539+0000] {standard_task_runner.py:91} INFO - Job 105: Subtask generate_and_insert_data
[2024-06-29T21:39:51.555+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:39:51.583+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T17:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T17:10:00+00:00'
[2024-06-29T21:39:51.584+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:39:51.640+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:39:51.640+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:39:51.641+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:39:51.641+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:39:51.641+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:39:51.646+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T17:10:00+00:00, execution_date=20230101T171000, start_date=20240629T213951, end_date=20240629T213951
[2024-06-29T21:39:51.683+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:39:51.691+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:39:51.692+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:03:39.683+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:03:39.694+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [queued]>
[2024-06-29T22:03:39.696+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [queued]>
[2024-06-29T22:03:39.696+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:03:39.701+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 17:10:00+00:00
[2024-06-29T22:03:39.703+0000] {standard_task_runner.py:63} INFO - Started process 1537 to run task
[2024-06-29T22:03:39.704+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T17:10:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpao22cs4c']
[2024-06-29T22:03:39.705+0000] {standard_task_runner.py:91} INFO - Job 105: Subtask generate_and_insert_data
[2024-06-29T22:03:39.722+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T17:10:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:03:39.750+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T17:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T17:10:00+00:00'
[2024-06-29T22:03:39.751+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:03:39.807+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:03:39.807+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:03:39.807+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:03:39.808+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:03:39.808+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:03:39.812+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T17:10:00+00:00, execution_date=20230101T171000, start_date=20240629T220339, end_date=20240629T220339
[2024-06-29T22:03:39.845+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:03:39.852+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:03:39.852+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
