[2024-06-27T22:36:36.464+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:36:36.474+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T18:10:00+00:00 [queued]>
[2024-06-27T22:36:36.476+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T18:10:00+00:00 [queued]>
[2024-06-27T22:36:36.477+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:36:36.481+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 18:10:00+00:00
[2024-06-27T22:36:36.483+0000] {standard_task_runner.py:63} INFO - Started process 1860 to run task
[2024-06-27T22:36:36.484+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T18:10:00+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmppmcq5vr_']
[2024-06-27T22:36:36.484+0000] {standard_task_runner.py:91} INFO - Job 128: Subtask generate_and_insert_data
[2024-06-27T22:36:36.500+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T18:10:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:36:36.528+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T18:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T18:10:00+00:00'
[2024-06-27T22:36:36.528+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:36:36.561+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:36:36.562+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:36:36.562+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:36:36.566+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T18:10:00+00:00, execution_date=20230101T181000, start_date=20240627T223636, end_date=20240627T223636
[2024-06-27T22:36:36.587+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:36:36.593+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:36:36.593+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:18:46.594+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:18:46.607+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T18:10:00+00:00 [queued]>
[2024-06-28T18:18:46.610+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T18:10:00+00:00 [queued]>
[2024-06-28T18:18:46.610+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:18:46.615+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 18:10:00+00:00
[2024-06-28T18:18:46.618+0000] {standard_task_runner.py:63} INFO - Started process 3096 to run task
[2024-06-28T18:18:46.619+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T18:10:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpe18qhm0_']
[2024-06-28T18:18:46.620+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask generate_and_insert_data
[2024-06-28T18:18:46.641+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T18:10:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:18:46.678+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T18:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T18:10:00+00:00'
[2024-06-28T18:18:46.679+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:18:46.742+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:18:46.743+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:18:46.743+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:18:46.743+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:18:46.743+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:18:46.749+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T18:10:00+00:00, execution_date=20230101T181000, start_date=20240628T181846, end_date=20240628T181846
[2024-06-28T18:18:46.760+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:18:46.768+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:18:46.769+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
