[2024-06-27T22:33:44.517+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:33:44.527+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T22:33:44.529+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T22:33:44.530+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:33:44.534+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-27T22:33:44.535+0000] {standard_task_runner.py:63} INFO - Started process 534 to run task
[2024-06-27T22:33:44.537+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp69yougle']
[2024-06-27T22:33:44.537+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask generate_and_insert_data
[2024-06-27T22:33:44.554+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:33:44.582+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-27T22:33:44.582+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:33:44.616+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:33:44.616+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:33:44.616+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:33:44.621+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240627T223344, end_date=20240627T223344
[2024-06-27T22:33:44.638+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:33:44.644+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:33:44.645+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T22:52:34.508+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:52:34.518+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T22:52:34.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T22:52:34.521+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:52:34.525+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-27T22:52:34.526+0000] {standard_task_runner.py:63} INFO - Started process 547 to run task
[2024-06-27T22:52:34.527+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpblqkdfmz']
[2024-06-27T22:52:34.528+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask generate_and_insert_data
[2024-06-27T22:52:34.544+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host a70edf9d8581
[2024-06-27T22:52:34.572+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-27T22:52:34.573+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:52:34.605+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:52:34.605+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T22:52:34.605+0000] {logging_mixin.py:188} INFO - stderr: python3: can't open file '/opt/airflow/./generator/ecomm_generator.py': [Errno 2] No such file or directory
[2024-06-27T22:52:34.605+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:52:34.606+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:52:34.610+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240627T225234, end_date=20240627T225234
[2024-06-27T22:52:34.629+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:52:34.636+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:52:34.636+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T23:00:17.577+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T23:00:17.588+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T23:00:17.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T23:00:17.590+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T23:00:17.595+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-27T23:00:17.596+0000] {standard_task_runner.py:63} INFO - Started process 521 to run task
[2024-06-27T23:00:17.597+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpkvmry8ps']
[2024-06-27T23:00:17.598+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask generate_and_insert_data
[2024-06-27T23:00:17.615+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 5cc71d4b298c
[2024-06-27T23:00:17.643+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-27T23:00:17.643+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T23:00:17.700+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-27T23:00:17.700+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T23:00:17.700+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-27T23:00:17.701+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T23:00:17.701+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T23:00:17.706+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240627T230017, end_date=20240627T230017
[2024-06-27T23:00:17.750+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T23:00:17.757+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T23:00:17.758+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T23:10:00.225+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T23:10:00.234+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T23:10:00.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T23:10:00.237+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T23:10:00.241+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-27T23:10:00.242+0000] {standard_task_runner.py:63} INFO - Started process 562 to run task
[2024-06-27T23:10:00.243+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp19sel9no']
[2024-06-27T23:10:00.244+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask generate_and_insert_data
[2024-06-27T23:10:00.260+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 7147f8a4dc9f
[2024-06-27T23:10:00.288+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-27T23:10:00.289+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T23:10:00.345+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-27T23:10:00.345+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T23:10:00.346+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-27T23:10:00.346+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T23:10:00.346+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T23:10:00.351+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240627T231000, end_date=20240627T231000
[2024-06-27T23:10:00.386+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T23:10:00.392+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T23:10:00.393+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T23:13:34.780+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T23:13:34.791+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T23:13:34.794+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-27T23:13:34.794+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T23:13:34.798+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-27T23:13:34.800+0000] {standard_task_runner.py:63} INFO - Started process 521 to run task
[2024-06-27T23:13:34.801+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpr1ztakcw']
[2024-06-27T23:13:34.802+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask generate_and_insert_data
[2024-06-27T23:13:34.818+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 4bd55eb76a74
[2024-06-27T23:13:34.847+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-27T23:13:34.848+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T23:13:34.904+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-27T23:13:34.904+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T23:13:34.904+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-27T23:13:34.905+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T23:13:34.905+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T23:13:34.910+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240627T231334, end_date=20240627T231334
[2024-06-27T23:13:34.944+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T23:13:34.951+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T23:13:34.952+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:13:52.891+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:13:52.901+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-28T18:13:52.903+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-28T18:13:52.904+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:13:52.908+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-28T18:13:52.909+0000] {standard_task_runner.py:63} INFO - Started process 547 to run task
[2024-06-28T18:13:52.910+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpcrxew9m1']
[2024-06-28T18:13:52.911+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask generate_and_insert_data
[2024-06-28T18:13:52.927+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:13:52.955+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-28T18:13:52.955+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:13:53.009+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:13:53.009+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:13:53.010+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:13:53.010+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:13:53.010+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:13:53.015+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240628T181352, end_date=20240628T181353
[2024-06-28T18:13:53.052+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:13:53.059+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:13:53.059+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:21:08.912+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:21:08.922+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-28T18:21:08.925+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-28T18:21:08.925+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:21:08.929+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-28T18:21:08.931+0000] {standard_task_runner.py:63} INFO - Started process 547 to run task
[2024-06-28T18:21:08.932+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp5u7fh7lf']
[2024-06-28T18:21:08.933+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask generate_and_insert_data
[2024-06-28T18:21:08.951+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 6570e5857071
[2024-06-28T18:21:08.979+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-28T18:21:08.979+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:21:09.038+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:21:09.038+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:21:09.039+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:21:09.039+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:21:09.039+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:21:09.044+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240628T182108, end_date=20240628T182109
[2024-06-28T18:21:09.079+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:21:09.085+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:21:09.086+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:31:09.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:31:09.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-28T18:31:09.886+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-28T18:31:09.886+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:31:09.891+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-28T18:31:09.893+0000] {standard_task_runner.py:63} INFO - Started process 534 to run task
[2024-06-28T18:31:09.894+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpjuaeuwjj']
[2024-06-28T18:31:09.894+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask generate_and_insert_data
[2024-06-28T18:31:09.911+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 50bf780463b8
[2024-06-28T18:31:09.941+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-28T18:31:09.941+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:31:09.998+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:31:09.998+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:31:09.999+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:31:09.999+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:31:09.999+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:31:10.004+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240628T183109, end_date=20240628T183110
[2024-06-28T18:31:10.042+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:31:10.050+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:31:10.050+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T22:14:22.175+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T22:14:22.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-28T22:14:22.189+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-28T22:14:22.189+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T22:14:22.193+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-28T22:14:22.195+0000] {standard_task_runner.py:63} INFO - Started process 562 to run task
[2024-06-28T22:14:22.196+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpythlj16t']
[2024-06-28T22:14:22.196+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask generate_and_insert_data
[2024-06-28T22:14:22.213+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 619125b6796e
[2024-06-28T22:14:22.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-28T22:14:22.243+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T22:14:22.297+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T22:14:22.297+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T22:14:22.298+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T22:14:22.298+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T22:14:22.298+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T22:14:22.303+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240628T221422, end_date=20240628T221422
[2024-06-28T22:14:22.352+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T22:14:22.360+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T22:14:22.360+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:37:09.365+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:37:09.375+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-29T21:37:09.378+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-29T21:37:09.378+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:37:09.383+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-29T21:37:09.384+0000] {standard_task_runner.py:63} INFO - Started process 302 to run task
[2024-06-29T21:37:09.385+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpl6edin18']
[2024-06-29T21:37:09.386+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask generate_and_insert_data
[2024-06-29T21:37:09.403+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:37:09.433+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-29T21:37:09.434+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:37:09.494+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:37:09.495+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:37:09.495+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:37:09.495+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:37:09.495+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:37:09.500+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240629T213709, end_date=20240629T213709
[2024-06-29T21:37:09.529+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:37:09.536+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:37:09.536+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:49:26.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:49:26.190+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-29T21:49:26.193+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-29T21:49:26.193+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:49:26.198+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-29T21:49:26.200+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-06-29T21:49:26.201+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpijhs5owk']
[2024-06-29T21:49:26.202+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask generate_and_insert_data
[2024-06-29T21:49:26.220+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 0b7af056b90c
[2024-06-29T21:49:26.249+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-29T21:49:26.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:49:26.305+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:49:26.305+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:49:26.306+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:49:26.306+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:49:26.306+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:49:26.311+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240629T214926, end_date=20240629T214926
[2024-06-29T21:49:26.347+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:49:26.354+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:49:26.354+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:00:58.863+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:00:58.874+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-29T22:00:58.876+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [queued]>
[2024-06-29T22:00:58.876+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:00:58.880+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 03:00:00+00:00
[2024-06-29T22:00:58.882+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-06-29T22:00:58.883+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T03:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp3pidlyct']
[2024-06-29T22:00:58.883+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask generate_and_insert_data
[2024-06-29T22:00:58.900+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T03:00:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:00:58.928+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T03:00:00+00:00'
[2024-06-29T22:00:58.929+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:00:58.984+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:00:58.985+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:00:58.985+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:00:58.985+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:00:58.985+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:00:58.990+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T03:00:00+00:00, execution_date=20230101T030000, start_date=20240629T220058, end_date=20240629T220058
[2024-06-29T22:00:59.030+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:00:59.038+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:00:59.038+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
