[2024-06-27T22:34:07.009+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:34:07.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-27T22:34:07.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-27T22:34:07.022+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:34:07.026+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:00:00+00:00
[2024-06-27T22:34:07.027+0000] {standard_task_runner.py:63} INFO - Started process 704 to run task
[2024-06-27T22:34:07.028+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpf2n1cx5_']
[2024-06-27T22:34:07.029+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask generate_and_insert_data
[2024-06-27T22:34:07.045+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:34:07.072+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:00:00+00:00'
[2024-06-27T22:34:07.073+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:34:07.105+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:34:07.105+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:34:07.105+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:34:07.110+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:00:00+00:00, execution_date=20230101T050000, start_date=20240627T223407, end_date=20240627T223407
[2024-06-27T22:34:07.131+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:34:07.138+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:34:07.138+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T22:53:12.324+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:53:12.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-27T22:53:12.337+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-27T22:53:12.337+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:53:12.341+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:00:00+00:00
[2024-06-27T22:53:12.343+0000] {standard_task_runner.py:63} INFO - Started process 883 to run task
[2024-06-27T22:53:12.344+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp50uimkyw']
[2024-06-27T22:53:12.345+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask generate_and_insert_data
[2024-06-27T22:53:12.361+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [running]> on host a70edf9d8581
[2024-06-27T22:53:12.391+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:00:00+00:00'
[2024-06-27T22:53:12.392+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:53:12.428+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:53:12.428+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T22:53:12.429+0000] {logging_mixin.py:188} INFO - stderr: python3: can't open file '/opt/airflow/./generator/ecomm_generator.py': [Errno 2] No such file or directory
[2024-06-27T22:53:12.429+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:53:12.429+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:53:12.434+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:00:00+00:00, execution_date=20230101T050000, start_date=20240627T225312, end_date=20240627T225312
[2024-06-27T22:53:12.441+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:53:12.447+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:53:12.447+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:14:31.926+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:14:31.937+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-28T18:14:31.939+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-28T18:14:31.939+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:14:31.944+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:00:00+00:00
[2024-06-28T18:14:31.945+0000] {standard_task_runner.py:63} INFO - Started process 896 to run task
[2024-06-28T18:14:31.947+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpqrullczo']
[2024-06-28T18:14:31.947+0000] {standard_task_runner.py:91} INFO - Job 63: Subtask generate_and_insert_data
[2024-06-28T18:14:31.965+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:14:31.993+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:00:00+00:00'
[2024-06-28T18:14:31.993+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:14:32.050+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:14:32.050+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:14:32.050+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:14:32.050+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:14:32.051+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:14:32.056+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:00:00+00:00, execution_date=20230101T050000, start_date=20240628T181431, end_date=20240628T181432
[2024-06-28T18:14:32.091+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:14:32.098+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:14:32.098+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:21:36.690+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:21:36.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-28T18:21:36.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-28T18:21:36.706+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:21:36.711+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:00:00+00:00
[2024-06-28T18:21:36.713+0000] {standard_task_runner.py:63} INFO - Started process 764 to run task
[2024-06-28T18:21:36.714+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpw17h7gmn']
[2024-06-28T18:21:36.715+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask generate_and_insert_data
[2024-06-28T18:21:36.737+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [running]> on host 6570e5857071
[2024-06-28T18:21:36.780+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:00:00+00:00'
[2024-06-28T18:21:36.780+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:21:36.844+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:21:36.845+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:21:36.845+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:21:36.845+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:21:36.845+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:21:36.851+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:00:00+00:00, execution_date=20230101T050000, start_date=20240628T182136, end_date=20240628T182136
[2024-06-28T18:21:36.859+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:21:36.867+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:21:36.868+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:31:32.661+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:31:32.671+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-28T18:31:32.674+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-28T18:31:32.674+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:31:32.679+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:00:00+00:00
[2024-06-28T18:31:32.680+0000] {standard_task_runner.py:63} INFO - Started process 704 to run task
[2024-06-28T18:31:32.681+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpqfhdv4fn']
[2024-06-28T18:31:32.682+0000] {standard_task_runner.py:91} INFO - Job 49: Subtask generate_and_insert_data
[2024-06-28T18:31:32.698+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [running]> on host 50bf780463b8
[2024-06-28T18:31:32.726+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:00:00+00:00'
[2024-06-28T18:31:32.726+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:31:32.783+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:31:32.783+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:31:32.783+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:31:32.784+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:31:32.784+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:31:32.789+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:00:00+00:00, execution_date=20230101T050000, start_date=20240628T183132, end_date=20240628T183132
[2024-06-28T18:31:32.824+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:31:32.831+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:31:32.831+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:37:32.458+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:37:32.467+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-29T21:37:32.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-29T21:37:32.470+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:37:32.474+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:00:00+00:00
[2024-06-29T21:37:32.476+0000] {standard_task_runner.py:63} INFO - Started process 478 to run task
[2024-06-29T21:37:32.477+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpuwa_1hin']
[2024-06-29T21:37:32.478+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask generate_and_insert_data
[2024-06-29T21:37:32.495+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:37:32.523+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:00:00+00:00'
[2024-06-29T21:37:32.523+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:37:32.578+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:37:32.578+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:37:32.578+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:37:32.579+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:37:32.579+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:37:32.584+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:00:00+00:00, execution_date=20230101T050000, start_date=20240629T213732, end_date=20240629T213732
[2024-06-29T21:37:32.625+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:37:32.633+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:37:32.633+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:49:49.199+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:49:49.208+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-29T21:49:49.211+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-29T21:49:49.211+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:49:49.215+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:00:00+00:00
[2024-06-29T21:49:49.216+0000] {standard_task_runner.py:63} INFO - Started process 479 to run task
[2024-06-29T21:49:49.217+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp3kddjlnm']
[2024-06-29T21:49:49.218+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask generate_and_insert_data
[2024-06-29T21:49:49.234+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [running]> on host 0b7af056b90c
[2024-06-29T21:49:49.262+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:00:00+00:00'
[2024-06-29T21:49:49.262+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:49:49.319+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:49:49.319+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:49:49.319+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:49:49.319+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:49:49.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:49:49.324+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:00:00+00:00, execution_date=20230101T050000, start_date=20240629T214949, end_date=20240629T214949
[2024-06-29T21:49:49.359+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:49:49.366+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:49:49.366+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:01:22.337+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:01:22.348+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-29T22:01:22.350+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [queued]>
[2024-06-29T22:01:22.351+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:01:22.355+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 05:00:00+00:00
[2024-06-29T22:01:22.357+0000] {standard_task_runner.py:63} INFO - Started process 478 to run task
[2024-06-29T22:01:22.358+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T05:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmprttfw7lj']
[2024-06-29T22:01:22.359+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask generate_and_insert_data
[2024-06-29T22:01:22.376+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T05:00:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:01:22.405+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T05:00:00+00:00'
[2024-06-29T22:01:22.405+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:01:22.462+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:01:22.462+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:01:22.463+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:01:22.463+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:01:22.463+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:01:22.468+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T05:00:00+00:00, execution_date=20230101T050000, start_date=20240629T220122, end_date=20240629T220122
[2024-06-29T22:01:22.510+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:01:22.517+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:01:22.518+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
