[2024-06-27T22:33:43.090+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:33:43.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T22:33:43.104+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T22:33:43.104+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:33:43.109+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-27T22:33:43.111+0000] {standard_task_runner.py:63} INFO - Started process 520 to run task
[2024-06-27T22:33:43.112+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp9zmvzy1n']
[2024-06-27T22:33:43.113+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask generate_and_insert_data
[2024-06-27T22:33:43.134+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:33:43.168+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-27T22:33:43.168+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:33:43.206+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:33:43.207+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:33:43.207+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:33:43.212+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240627T223343, end_date=20240627T223343
[2024-06-27T22:33:43.255+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:33:43.263+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:33:43.264+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T22:52:33.044+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:52:33.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T22:52:33.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T22:52:33.058+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:52:33.063+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-27T22:52:33.064+0000] {standard_task_runner.py:63} INFO - Started process 533 to run task
[2024-06-27T22:52:33.065+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpnxcwjk8b']
[2024-06-27T22:52:33.066+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask generate_and_insert_data
[2024-06-27T22:52:33.087+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host a70edf9d8581
[2024-06-27T22:52:33.121+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-27T22:52:33.122+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:52:33.160+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:52:33.160+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T22:52:33.160+0000] {logging_mixin.py:188} INFO - stderr: python3: can't open file '/opt/airflow/./generator/ecomm_generator.py': [Errno 2] No such file or directory
[2024-06-27T22:52:33.160+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:52:33.160+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:52:33.165+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240627T225233, end_date=20240627T225233
[2024-06-27T22:52:33.213+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:52:33.220+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:52:33.220+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T23:00:16.083+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T23:00:16.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T23:00:16.097+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T23:00:16.098+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T23:00:16.102+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-27T23:00:16.104+0000] {standard_task_runner.py:63} INFO - Started process 507 to run task
[2024-06-27T23:00:16.105+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpof4i_djh']
[2024-06-27T23:00:16.106+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask generate_and_insert_data
[2024-06-27T23:00:16.126+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 5cc71d4b298c
[2024-06-27T23:00:16.162+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-27T23:00:16.162+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T23:00:16.224+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-27T23:00:16.224+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T23:00:16.225+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-27T23:00:16.225+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T23:00:16.225+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T23:00:16.230+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240627T230016, end_date=20240627T230016
[2024-06-27T23:00:16.256+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T23:00:16.263+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T23:00:16.267+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T23:09:55.909+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T23:09:55.921+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T23:09:55.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T23:09:55.924+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T23:09:55.929+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-27T23:09:55.931+0000] {standard_task_runner.py:63} INFO - Started process 520 to run task
[2024-06-27T23:09:55.932+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpr36nz1ti']
[2024-06-27T23:09:55.933+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask generate_and_insert_data
[2024-06-27T23:09:55.954+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 7147f8a4dc9f
[2024-06-27T23:09:55.989+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-27T23:09:55.990+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T23:09:56.068+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-27T23:09:56.068+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T23:09:56.068+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-27T23:09:56.069+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T23:09:56.069+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T23:09:56.075+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240627T230955, end_date=20240627T230956
[2024-06-27T23:09:56.115+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T23:09:56.122+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T23:09:56.122+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T23:13:33.322+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T23:13:33.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T23:13:33.336+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-27T23:13:33.336+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T23:13:33.341+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-27T23:13:33.343+0000] {standard_task_runner.py:63} INFO - Started process 507 to run task
[2024-06-27T23:13:33.344+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmppsj8h8sc']
[2024-06-27T23:13:33.345+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask generate_and_insert_data
[2024-06-27T23:13:33.368+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 4bd55eb76a74
[2024-06-27T23:13:33.405+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-27T23:13:33.405+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T23:13:33.468+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-27T23:13:33.468+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T23:13:33.468+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-27T23:13:33.468+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T23:13:33.469+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T23:13:33.474+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240627T231333, end_date=20240627T231333
[2024-06-27T23:13:33.484+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T23:13:33.491+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T23:13:33.492+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:13:51.423+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:13:51.434+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-28T18:13:51.437+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-28T18:13:51.437+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:13:51.442+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-28T18:13:51.443+0000] {standard_task_runner.py:63} INFO - Started process 533 to run task
[2024-06-28T18:13:51.444+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpdqg6w99_']
[2024-06-28T18:13:51.445+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask generate_and_insert_data
[2024-06-28T18:13:51.464+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:13:51.495+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-28T18:13:51.495+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:13:51.557+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:13:51.557+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:13:51.558+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:13:51.558+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:13:51.558+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:13:51.563+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240628T181351, end_date=20240628T181351
[2024-06-28T18:13:51.584+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:13:51.592+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:13:51.592+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:21:07.396+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:21:07.411+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-28T18:21:07.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-28T18:21:07.415+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:21:07.423+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-28T18:21:07.425+0000] {standard_task_runner.py:63} INFO - Started process 533 to run task
[2024-06-28T18:21:07.427+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp5fzjzd_x']
[2024-06-28T18:21:07.427+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask generate_and_insert_data
[2024-06-28T18:21:07.447+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 6570e5857071
[2024-06-28T18:21:07.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-28T18:21:07.481+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:21:07.572+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:21:07.573+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:21:07.573+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:21:07.573+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:21:07.574+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:21:07.581+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240628T182107, end_date=20240628T182107
[2024-06-28T18:21:07.614+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:21:07.621+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:21:07.622+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:31:08.399+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:31:08.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-28T18:31:08.413+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-28T18:31:08.413+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:31:08.417+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-28T18:31:08.419+0000] {standard_task_runner.py:63} INFO - Started process 520 to run task
[2024-06-28T18:31:08.421+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmphh0srsuh']
[2024-06-28T18:31:08.421+0000] {standard_task_runner.py:91} INFO - Job 36: Subtask generate_and_insert_data
[2024-06-28T18:31:08.439+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 50bf780463b8
[2024-06-28T18:31:08.469+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-28T18:31:08.469+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:31:08.526+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:31:08.527+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:31:08.527+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:31:08.527+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:31:08.527+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:31:08.532+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240628T183108, end_date=20240628T183108
[2024-06-28T18:31:08.572+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:31:08.580+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:31:08.580+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T22:14:19.410+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T22:14:19.420+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-28T22:14:19.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-28T22:14:19.423+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T22:14:19.427+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-28T22:14:19.429+0000] {standard_task_runner.py:63} INFO - Started process 533 to run task
[2024-06-28T22:14:19.430+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpqvfb_fct']
[2024-06-28T22:14:19.431+0000] {standard_task_runner.py:91} INFO - Job 37: Subtask generate_and_insert_data
[2024-06-28T22:14:19.448+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 619125b6796e
[2024-06-28T22:14:19.476+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-28T22:14:19.477+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T22:14:19.531+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T22:14:19.532+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T22:14:19.532+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T22:14:19.532+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T22:14:19.532+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T22:14:19.537+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240628T221419, end_date=20240628T221419
[2024-06-28T22:14:19.578+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T22:14:19.585+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T22:14:19.586+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:37:08.008+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:37:08.017+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-29T21:37:08.020+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-29T21:37:08.020+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:37:08.024+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-29T21:37:08.026+0000] {standard_task_runner.py:63} INFO - Started process 288 to run task
[2024-06-29T21:37:08.027+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp20ge8etb']
[2024-06-29T21:37:08.028+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask generate_and_insert_data
[2024-06-29T21:37:08.044+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:37:08.072+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-29T21:37:08.072+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:37:08.125+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:37:08.126+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:37:08.126+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:37:08.126+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:37:08.126+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:37:08.131+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240629T213708, end_date=20240629T213708
[2024-06-29T21:37:08.171+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:37:08.178+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:37:08.179+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:49:24.764+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:49:24.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-29T21:49:24.777+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-29T21:49:24.777+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:49:24.781+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-29T21:49:24.783+0000] {standard_task_runner.py:63} INFO - Started process 289 to run task
[2024-06-29T21:49:24.784+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpsil0xvdg']
[2024-06-29T21:49:24.785+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask generate_and_insert_data
[2024-06-29T21:49:24.801+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 0b7af056b90c
[2024-06-29T21:49:24.829+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-29T21:49:24.829+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:49:24.885+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:49:24.885+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:49:24.885+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:49:24.885+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:49:24.886+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:49:24.891+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240629T214924, end_date=20240629T214924
[2024-06-29T21:49:24.932+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:49:24.939+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:49:24.940+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:00:57.437+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:00:57.447+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-29T22:00:57.450+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [queued]>
[2024-06-29T22:00:57.450+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:00:57.454+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 02:50:00+00:00
[2024-06-29T22:00:57.456+0000] {standard_task_runner.py:63} INFO - Started process 289 to run task
[2024-06-29T22:00:57.458+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T02:50:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpg2jxpb49']
[2024-06-29T22:00:57.459+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask generate_and_insert_data
[2024-06-29T22:00:57.476+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T02:50:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:00:57.507+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T02:50:00+00:00'
[2024-06-29T22:00:57.507+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:00:57.563+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:00:57.563+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:00:57.563+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:00:57.563+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:00:57.564+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:00:57.568+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T02:50:00+00:00, execution_date=20230101T025000, start_date=20240629T220057, end_date=20240629T220057
[2024-06-29T22:00:57.607+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:00:57.614+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:00:57.615+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
