[2024-07-06T20:21:44.638+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: import_main_data.export_and_load_user_data scheduled__2024-07-06T04:00:00+00:00 [queued]>
[2024-07-06T20:21:44.641+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: import_main_data.export_and_load_user_data scheduled__2024-07-06T04:00:00+00:00 [queued]>
[2024-07-06T20:21:44.641+0000] {taskinstance.py:1308} INFO - Starting attempt 20 of 21
[2024-07-06T20:21:44.645+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): export_and_load_user_data> on 2024-07-06 04:00:00+00:00
[2024-07-06T20:21:44.646+0000] {standard_task_runner.py:57} INFO - Started process 164 to run task
[2024-07-06T20:21:44.648+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'import_main_data', 'export_and_load_user_data', 'scheduled__2024-07-06T04:00:00+00:00', '--job-id', '986', '--raw', '--subdir', 'DAGS_FOLDER/import_raw_data.py', '--cfg-path', '/tmp/tmpr6ma13qo']
[2024-07-06T20:21:44.648+0000] {standard_task_runner.py:85} INFO - Job 986: Subtask export_and_load_user_data
[2024-07-06T20:21:44.668+0000] {task_command.py:410} INFO - Running <TaskInstance: import_main_data.export_and_load_user_data scheduled__2024-07-06T04:00:00+00:00 [running]> on host c058add182a5
[2024-07-06T20:21:44.709+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='airflow@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='import_main_data' AIRFLOW_CTX_TASK_ID='export_and_load_user_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='20' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-06T04:00:00+00:00'
[2024-07-06T20:21:44.710+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-07-06T20:21:44.710+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "bash /opt/airflow/scripts/import_core_data.sh users user_id 'user_id, username, email, address, phone_number, created_at' ***ql://***:***@company_db:5432/company_db ***ql://***:***@company_dw:5432/company_dw"]
[2024-07-06T20:21:44.712+0000] {subprocess.py:86} INFO - Output:
[2024-07-06T20:21:44.748+0000] {subprocess.py:93} INFO - COPY 7557
[2024-07-06T20:21:44.761+0000] {subprocess.py:93} INFO - ERROR:  syntax error at or near "\"
[2024-07-06T20:21:44.762+0000] {subprocess.py:93} INFO - LINE 3:     \copy temp_users FROM '/tmp/temp_users.csv' CSV;
[2024-07-06T20:21:44.762+0000] {subprocess.py:93} INFO -             ^
[2024-07-06T20:21:44.762+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-06T20:21:44.768+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-06T20:21:44.769+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=import_main_data, task_id=export_and_load_user_data, execution_date=20240706T040000, start_date=20240706T202144, end_date=20240706T202144
[2024-07-06T20:21:44.775+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 986 for task export_and_load_user_data (Bash command failed. The command returned a non-zero exit code 1.; 164)
[2024-07-06T20:21:44.789+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-06T20:21:44.807+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
