[2024-07-04T00:23:51.726+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: marketing_generator.inser_email_marketing scheduled__2024-07-02T21:00:00+00:00 [queued]>
[2024-07-04T00:23:51.729+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: marketing_generator.inser_email_marketing scheduled__2024-07-02T21:00:00+00:00 [queued]>
[2024-07-04T00:23:51.729+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-07-04T00:23:51.733+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): inser_email_marketing> on 2024-07-02 21:00:00+00:00
[2024-07-04T00:23:51.735+0000] {standard_task_runner.py:57} INFO - Started process 1757 to run task
[2024-07-04T00:23:51.736+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'marketing_generator', 'inser_email_marketing', 'scheduled__2024-07-02T21:00:00+00:00', '--job-id', '606', '--raw', '--subdir', 'DAGS_FOLDER/marketing_generator_dag.py', '--cfg-path', '/tmp/tmp1s71hyrd']
[2024-07-04T00:23:51.737+0000] {standard_task_runner.py:85} INFO - Job 606: Subtask inser_email_marketing
[2024-07-04T00:23:51.755+0000] {task_command.py:410} INFO - Running <TaskInstance: marketing_generator.inser_email_marketing scheduled__2024-07-02T21:00:00+00:00 [running]> on host a4053733dbc4
[2024-07-04T00:23:51.789+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='marketing_generator' AIRFLOW_CTX_TASK_ID='inser_email_marketing' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T21:00:00+00:00'
[2024-07-04T00:23:51.790+0000] {logging_mixin.py:149} INFO - Inserting data into email_marketing from /opt/airflow/generator/fake_email_marketing_data.json...
[2024-07-04T00:23:51.803+0000] {logging_mixin.py:149} INFO - Error inserting data into email_marketing: not all arguments converted during string formatting
[2024-07-04T00:23:51.803+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/marketing_generator_dag.py", line 66, in insert_email_marketing
    insert_data("/opt/airflow/generator/fake_email_marketing_data.json", "email_marketing", insert_email_marketing_query)
  File "/opt/airflow/dags/marketing_generator_dag.py", line 60, in insert_data
    raise e
  File "/opt/airflow/dags/marketing_generator_dag.py", line 52, in insert_data
    cursor.execute(insert_query, tuple(record.values()))
TypeError: not all arguments converted during string formatting
[2024-07-04T00:23:51.808+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=marketing_generator, task_id=inser_email_marketing, execution_date=20240702T210000, start_date=20240704T002351, end_date=20240704T002351
[2024-07-04T00:23:51.812+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 606 for task inser_email_marketing (not all arguments converted during string formatting; 1757)
[2024-07-04T00:23:51.833+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-07-04T00:23:51.841+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
