[2024-06-27T22:34:32.109+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:34:32.119+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-27T22:34:32.122+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-27T22:34:32.122+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:34:32.126+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 07:10:00+00:00
[2024-06-27T22:34:32.128+0000] {standard_task_runner.py:63} INFO - Started process 896 to run task
[2024-06-27T22:34:32.129+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T07:10:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmppp9drf0q']
[2024-06-27T22:34:32.129+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask generate_and_insert_data
[2024-06-27T22:34:32.146+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:34:32.177+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:10:00+00:00'
[2024-06-27T22:34:32.177+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:34:32.211+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:34:32.211+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:34:32.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:34:32.216+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T07:10:00+00:00, execution_date=20230101T071000, start_date=20240627T223432, end_date=20240627T223432
[2024-06-27T22:34:32.229+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:34:32.236+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:34:32.236+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T22:53:37.237+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:53:37.248+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-27T22:53:37.250+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-27T22:53:37.250+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:53:37.254+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 07:10:00+00:00
[2024-06-27T22:53:37.256+0000] {standard_task_runner.py:63} INFO - Started process 1073 to run task
[2024-06-27T22:53:37.257+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T07:10:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpfhw6sssd']
[2024-06-27T22:53:37.258+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask generate_and_insert_data
[2024-06-27T22:53:37.273+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [running]> on host a70edf9d8581
[2024-06-27T22:53:37.301+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:10:00+00:00'
[2024-06-27T22:53:37.301+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:53:37.336+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:53:37.336+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T22:53:37.336+0000] {logging_mixin.py:188} INFO - stderr: python3: can't open file '/opt/airflow/./generator/ecomm_generator.py': [Errno 2] No such file or directory
[2024-06-27T22:53:37.336+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:53:37.337+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:53:37.341+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T07:10:00+00:00, execution_date=20230101T071000, start_date=20240627T225337, end_date=20240627T225337
[2024-06-27T22:53:37.358+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:53:37.364+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:53:37.365+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:15:13.383+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:15:13.394+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-28T18:15:13.397+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-28T18:15:13.397+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:15:13.401+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 07:10:00+00:00
[2024-06-28T18:15:13.403+0000] {standard_task_runner.py:63} INFO - Started process 1257 to run task
[2024-06-28T18:15:13.404+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T07:10:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpahnrk80u']
[2024-06-28T18:15:13.405+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask generate_and_insert_data
[2024-06-28T18:15:13.422+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:15:13.451+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:10:00+00:00'
[2024-06-28T18:15:13.452+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:15:13.508+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:15:13.509+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:15:13.509+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:15:13.509+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:15:13.509+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:15:13.514+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T07:10:00+00:00, execution_date=20230101T071000, start_date=20240628T181513, end_date=20240628T181513
[2024-06-28T18:15:13.550+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:15:13.556+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:15:13.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:21:59.997+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:22:00.008+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-28T18:22:00.010+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-28T18:22:00.010+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:22:00.015+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 07:10:00+00:00
[2024-06-28T18:22:00.017+0000] {standard_task_runner.py:63} INFO - Started process 948 to run task
[2024-06-28T18:22:00.018+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T07:10:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpavycss2d']
[2024-06-28T18:22:00.018+0000] {standard_task_runner.py:91} INFO - Job 66: Subtask generate_and_insert_data
[2024-06-28T18:22:00.036+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [running]> on host 6570e5857071
[2024-06-28T18:22:00.067+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:10:00+00:00'
[2024-06-28T18:22:00.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:22:00.124+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:22:00.124+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:22:00.125+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:22:00.125+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:22:00.125+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:22:00.130+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T07:10:00+00:00, execution_date=20230101T071000, start_date=20240628T182200, end_date=20240628T182200
[2024-06-28T18:22:00.158+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:22:00.164+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:22:00.165+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:31:58.044+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:31:58.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-28T18:31:58.057+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-28T18:31:58.057+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:31:58.061+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 07:10:00+00:00
[2024-06-28T18:31:58.063+0000] {standard_task_runner.py:63} INFO - Started process 896 to run task
[2024-06-28T18:31:58.064+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T07:10:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpipg8a45y']
[2024-06-28T18:31:58.065+0000] {standard_task_runner.py:91} INFO - Job 62: Subtask generate_and_insert_data
[2024-06-28T18:31:58.082+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [running]> on host 50bf780463b8
[2024-06-28T18:31:58.109+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:10:00+00:00'
[2024-06-28T18:31:58.110+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:31:58.166+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:31:58.167+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:31:58.167+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:31:58.167+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:31:58.167+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:31:58.172+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T07:10:00+00:00, execution_date=20230101T071000, start_date=20240628T183158, end_date=20240628T183158
[2024-06-28T18:31:58.214+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:31:58.221+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:31:58.222+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:37:57.691+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:37:57.700+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-29T21:37:57.703+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-29T21:37:57.703+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:37:57.707+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 07:10:00+00:00
[2024-06-29T21:37:57.709+0000] {standard_task_runner.py:63} INFO - Started process 661 to run task
[2024-06-29T21:37:57.710+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T07:10:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp_5l760jq']
[2024-06-29T21:37:57.711+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask generate_and_insert_data
[2024-06-29T21:37:57.728+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:37:57.756+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:10:00+00:00'
[2024-06-29T21:37:57.756+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:37:57.810+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:37:57.810+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:37:57.811+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:37:57.811+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:37:57.811+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:37:57.816+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T07:10:00+00:00, execution_date=20230101T071000, start_date=20240629T213757, end_date=20240629T213757
[2024-06-29T21:37:57.852+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:37:57.858+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:37:57.859+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:50:14.463+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:50:14.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-29T21:50:14.476+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-29T21:50:14.476+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:50:14.480+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 07:10:00+00:00
[2024-06-29T21:50:14.482+0000] {standard_task_runner.py:63} INFO - Started process 662 to run task
[2024-06-29T21:50:14.483+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T07:10:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpxlr3m9uh']
[2024-06-29T21:50:14.484+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask generate_and_insert_data
[2024-06-29T21:50:14.499+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [running]> on host 0b7af056b90c
[2024-06-29T21:50:14.527+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:10:00+00:00'
[2024-06-29T21:50:14.527+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:50:14.583+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:50:14.583+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:50:14.583+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:50:14.584+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:50:14.584+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:50:14.588+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T07:10:00+00:00, execution_date=20230101T071000, start_date=20240629T215014, end_date=20240629T215014
[2024-06-29T21:50:14.624+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:50:14.631+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:50:14.631+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:01:45.375+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:01:45.385+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-29T22:01:45.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [queued]>
[2024-06-29T22:01:45.388+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:01:45.392+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 07:10:00+00:00
[2024-06-29T22:01:45.394+0000] {standard_task_runner.py:63} INFO - Started process 661 to run task
[2024-06-29T22:01:45.395+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T07:10:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp5ozr_ozk']
[2024-06-29T22:01:45.396+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask generate_and_insert_data
[2024-06-29T22:01:45.413+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T07:10:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:01:45.443+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T07:10:00+00:00'
[2024-06-29T22:01:45.443+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:01:45.500+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:01:45.501+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:01:45.501+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:01:45.501+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:01:45.501+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:01:45.506+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T07:10:00+00:00, execution_date=20230101T071000, start_date=20240629T220145, end_date=20240629T220145
[2024-06-29T22:01:45.545+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:01:45.553+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:01:45.553+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
