[2024-06-27T22:36:03.979+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:36:03.988+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [queued]>
[2024-06-27T22:36:03.991+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [queued]>
[2024-06-27T22:36:03.991+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:36:03.995+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 15:20:00+00:00
[2024-06-27T22:36:03.997+0000] {standard_task_runner.py:63} INFO - Started process 1612 to run task
[2024-06-27T22:36:03.998+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T15:20:00+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpf6g2aakc']
[2024-06-27T22:36:03.999+0000] {standard_task_runner.py:91} INFO - Job 111: Subtask generate_and_insert_data
[2024-06-27T22:36:04.015+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:36:04.044+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T15:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T15:20:00+00:00'
[2024-06-27T22:36:04.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:36:04.077+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:36:04.078+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:36:04.078+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:36:04.083+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T15:20:00+00:00, execution_date=20230101T152000, start_date=20240627T223603, end_date=20240627T223604
[2024-06-27T22:36:04.105+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:36:04.111+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:36:04.112+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:17:50.252+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:17:50.263+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [queued]>
[2024-06-28T18:17:50.265+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [queued]>
[2024-06-28T18:17:50.266+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:17:50.270+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 15:20:00+00:00
[2024-06-28T18:17:50.273+0000] {standard_task_runner.py:63} INFO - Started process 2617 to run task
[2024-06-28T18:17:50.274+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T15:20:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpnf1eaqqq']
[2024-06-28T18:17:50.275+0000] {standard_task_runner.py:91} INFO - Job 186: Subtask generate_and_insert_data
[2024-06-28T18:17:50.293+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:17:50.324+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T15:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T15:20:00+00:00'
[2024-06-28T18:17:50.324+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:17:50.384+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:17:50.384+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:17:50.384+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:17:50.384+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:17:50.385+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:17:50.390+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T15:20:00+00:00, execution_date=20230101T152000, start_date=20240628T181750, end_date=20240628T181750
[2024-06-28T18:17:50.414+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:17:50.421+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:17:50.422+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:39:29.974+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:39:29.984+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [queued]>
[2024-06-29T21:39:29.987+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [queued]>
[2024-06-29T21:39:29.987+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:39:29.991+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 15:20:00+00:00
[2024-06-29T21:39:29.993+0000] {standard_task_runner.py:63} INFO - Started process 1374 to run task
[2024-06-29T21:39:29.994+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T15:20:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp3y97c29t']
[2024-06-29T21:39:29.995+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask generate_and_insert_data
[2024-06-29T21:39:30.012+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:39:30.040+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T15:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T15:20:00+00:00'
[2024-06-29T21:39:30.041+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:39:30.097+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:39:30.097+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:39:30.097+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:39:30.098+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:39:30.098+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:39:30.102+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T15:20:00+00:00, execution_date=20230101T152000, start_date=20240629T213929, end_date=20240629T213930
[2024-06-29T21:39:30.138+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:39:30.145+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:39:30.146+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:03:18.189+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:03:18.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [queued]>
[2024-06-29T22:03:18.201+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [queued]>
[2024-06-29T22:03:18.201+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:03:18.205+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 15:20:00+00:00
[2024-06-29T22:03:18.207+0000] {standard_task_runner.py:63} INFO - Started process 1374 to run task
[2024-06-29T22:03:18.208+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T15:20:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpix27ed32']
[2024-06-29T22:03:18.209+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask generate_and_insert_data
[2024-06-29T22:03:18.226+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:20:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:03:18.254+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T15:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T15:20:00+00:00'
[2024-06-29T22:03:18.254+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:03:18.311+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:03:18.311+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:03:18.311+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:03:18.311+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:03:18.312+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:03:18.316+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T15:20:00+00:00, execution_date=20230101T152000, start_date=20240629T220318, end_date=20240629T220318
[2024-06-29T22:03:18.353+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:03:18.360+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:03:18.361+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
