[0m03:14:08.942575 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff987b42e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff96c6f760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff96c6f700>]}


============================== 03:14:08.947160 | fb6b13ed-05db-4eeb-93db-7f222019ebd5 ==============================
[0m03:14:08.947160 [info ] [MainThread]: Running with dbt=1.8.3
[0m03:14:08.948253 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/opt/airflow/dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --profiles-dir /opt/airflow/dbt', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:14:08.948729 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /opt/airflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m03:14:08.949431 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.03241429, "process_user_time": 1.786612, "process_kernel_time": 0.049016, "process_mem_max_rss": "106460", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m03:14:08.949914 [debug] [MainThread]: Command `dbt run` failed at 03:14:08.949851 after 0.03 seconds
[0m03:14:08.950235 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff987b42e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff96c9e640>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff96c9ef10>]}
[0m03:14:08.950505 [debug] [MainThread]: Flushing usage events
[0m03:17:34.826531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff64f34550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff62f876a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff62f87640>]}


============================== 03:17:34.829904 | c6ecf916-538a-45dc-8821-1d8c8597591f ==============================
[0m03:17:34.829904 [info ] [MainThread]: Running with dbt=1.8.3
[0m03:17:34.830445 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/opt/airflow/dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run --profiles-dir /opt/airflow/dbt', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m03:17:34.830887 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /opt/airflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m03:17:34.831562 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.029585375, "process_user_time": 1.816878, "process_kernel_time": 0.061961, "process_mem_max_rss": "112736", "process_out_blocks": "944", "command_success": false, "process_in_blocks": "0"}
[0m03:17:34.832052 [debug] [MainThread]: Command `dbt run` failed at 03:17:34.831998 after 0.03 seconds
[0m03:17:34.832372 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff64f34550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff631e76a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff62fb9430>]}
[0m03:17:34.832706 [debug] [MainThread]: Flushing usage events
[0m05:19:21.809007 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff96ce6ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94d78790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff94d78730>]}


============================== 05:19:21.813540 | 815d38c4-dd25-4e96-9d5a-b5c92062fa3d ==============================
[0m05:19:21.813540 [info ] [MainThread]: Running with dbt=1.8.3
[0m05:19:21.814146 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/opt/airflow/dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --profiles-dir /opt/airflow/dbt', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m05:19:21.814595 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /opt/airflow/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m05:19:21.815258 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.031687625, "process_user_time": 1.881743, "process_kernel_time": 0.123785, "process_mem_max_rss": "108620", "process_in_blocks": "8", "process_out_blocks": "944", "command_success": false}
[0m05:19:21.815750 [debug] [MainThread]: Command `dbt run` failed at 05:19:21.815680 after 0.03 seconds
[0m05:19:21.816096 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff96ce6ac0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff953a72e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0xffff953a7880>]}
[0m05:19:21.816423 [debug] [MainThread]: Flushing usage events
