[2024-06-27T22:36:07.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:36:07.743+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [queued]>
[2024-06-27T22:36:07.746+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [queued]>
[2024-06-27T22:36:07.746+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:36:07.750+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 15:40:00+00:00
[2024-06-27T22:36:07.752+0000] {standard_task_runner.py:63} INFO - Started process 1640 to run task
[2024-06-27T22:36:07.753+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T15:40:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpmcu7yjv3']
[2024-06-27T22:36:07.753+0000] {standard_task_runner.py:91} INFO - Job 113: Subtask generate_and_insert_data
[2024-06-27T22:36:07.769+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:36:07.798+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T15:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T15:40:00+00:00'
[2024-06-27T22:36:07.799+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:36:07.831+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:36:07.832+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:36:07.832+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:36:07.837+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T15:40:00+00:00, execution_date=20230101T154000, start_date=20240627T223607, end_date=20240627T223607
[2024-06-27T22:36:07.855+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:36:07.861+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:36:07.862+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:17:57.697+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:17:57.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [queued]>
[2024-06-28T18:17:57.710+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [queued]>
[2024-06-28T18:17:57.710+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:17:57.715+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 15:40:00+00:00
[2024-06-28T18:17:57.717+0000] {standard_task_runner.py:63} INFO - Started process 2686 to run task
[2024-06-28T18:17:57.718+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T15:40:00+00:00', '--job-id', '191', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmprgb15azz']
[2024-06-28T18:17:57.719+0000] {standard_task_runner.py:91} INFO - Job 191: Subtask generate_and_insert_data
[2024-06-28T18:17:57.736+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:17:57.770+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T15:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T15:40:00+00:00'
[2024-06-28T18:17:57.770+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:17:57.830+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:17:57.830+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:17:57.830+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:17:57.830+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:17:57.831+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:17:57.836+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T15:40:00+00:00, execution_date=20230101T154000, start_date=20240628T181757, end_date=20240628T181757
[2024-06-28T18:17:57.858+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:17:57.866+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:17:57.866+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:39:33.697+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:39:33.707+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [queued]>
[2024-06-29T21:39:33.709+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [queued]>
[2024-06-29T21:39:33.709+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:39:33.714+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 15:40:00+00:00
[2024-06-29T21:39:33.716+0000] {standard_task_runner.py:63} INFO - Started process 1402 to run task
[2024-06-29T21:39:33.717+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T15:40:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp2t01cre_']
[2024-06-29T21:39:33.717+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask generate_and_insert_data
[2024-06-29T21:39:33.735+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:39:33.763+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T15:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T15:40:00+00:00'
[2024-06-29T21:39:33.763+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:39:33.820+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:39:33.820+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:39:33.820+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:39:33.820+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:39:33.821+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:39:33.825+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T15:40:00+00:00, execution_date=20230101T154000, start_date=20240629T213933, end_date=20240629T213933
[2024-06-29T21:39:33.866+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:39:33.874+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:39:33.874+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:03:22.078+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:03:22.087+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [queued]>
[2024-06-29T22:03:22.090+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [queued]>
[2024-06-29T22:03:22.090+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:03:22.094+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 15:40:00+00:00
[2024-06-29T22:03:22.096+0000] {standard_task_runner.py:63} INFO - Started process 1402 to run task
[2024-06-29T22:03:22.097+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T15:40:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpqn3c1bqt']
[2024-06-29T22:03:22.098+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask generate_and_insert_data
[2024-06-29T22:03:22.114+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T15:40:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:03:22.142+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T15:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T15:40:00+00:00'
[2024-06-29T22:03:22.142+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:03:22.199+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:03:22.199+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:03:22.199+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:03:22.199+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:03:22.200+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:03:22.204+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T15:40:00+00:00, execution_date=20230101T154000, start_date=20240629T220322, end_date=20240629T220322
[2024-06-29T22:03:22.244+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:03:22.252+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:03:22.252+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
