[2024-06-29T22:08:20.581+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:08:20.591+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T17:40:00+00:00 [queued]>
[2024-06-29T22:08:20.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T17:40:00+00:00 [queued]>
[2024-06-29T22:08:20.594+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:08:20.599+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-02 17:40:00+00:00
[2024-06-29T22:08:20.601+0000] {standard_task_runner.py:63} INFO - Started process 3676 to run task
[2024-06-29T22:08:20.602+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-02T17:40:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpc617vezf']
[2024-06-29T22:08:20.603+0000] {standard_task_runner.py:91} INFO - Job 252: Subtask generate_and_insert_data
[2024-06-29T22:08:20.620+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-02T17:40:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:08:20.648+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-02T17:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-02T17:40:00+00:00'
[2024-06-29T22:08:20.649+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:08:20.706+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:08:20.706+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:08:20.706+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:08:20.706+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:08:20.707+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:08:20.711+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-02T17:40:00+00:00, execution_date=20230102T174000, start_date=20240629T220820, end_date=20240629T220820
[2024-06-29T22:08:20.741+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:08:20.748+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:08:20.748+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
