[2024-06-27T22:34:28.321+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:34:28.331+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-27T22:34:28.333+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-27T22:34:28.333+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:34:28.337+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 06:50:00+00:00
[2024-06-27T22:34:28.339+0000] {standard_task_runner.py:63} INFO - Started process 868 to run task
[2024-06-27T22:34:28.340+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T06:50:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpnv3m8asv']
[2024-06-27T22:34:28.341+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask generate_and_insert_data
[2024-06-27T22:34:28.357+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:34:28.385+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T06:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T06:50:00+00:00'
[2024-06-27T22:34:28.385+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:34:28.417+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:34:28.418+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:34:28.418+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:34:28.423+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T06:50:00+00:00, execution_date=20230101T065000, start_date=20240627T223428, end_date=20240627T223428
[2024-06-27T22:34:28.441+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:34:28.448+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:34:28.448+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-27T22:53:33.524+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:53:33.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-27T22:53:33.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-27T22:53:33.537+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:53:33.541+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 06:50:00+00:00
[2024-06-27T22:53:33.543+0000] {standard_task_runner.py:63} INFO - Started process 1037 to run task
[2024-06-27T22:53:33.544+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T06:50:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpyzo4hkwr']
[2024-06-27T22:53:33.545+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask generate_and_insert_data
[2024-06-27T22:53:33.561+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [running]> on host a70edf9d8581
[2024-06-27T22:53:33.589+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T06:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T06:50:00+00:00'
[2024-06-27T22:53:33.589+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:53:33.622+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:53:33.623+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-27T22:53:33.623+0000] {logging_mixin.py:188} INFO - stderr: python3: can't open file '/opt/airflow/./generator/ecomm_generator.py': [Errno 2] No such file or directory
[2024-06-27T22:53:33.623+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:53:33.623+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:53:33.628+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T06:50:00+00:00, execution_date=20230101T065000, start_date=20240627T225333, end_date=20240627T225333
[2024-06-27T22:53:33.649+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:53:33.656+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:53:33.656+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:15:05.328+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:15:05.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-28T18:15:05.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-28T18:15:05.341+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:15:05.346+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 06:50:00+00:00
[2024-06-28T18:15:05.347+0000] {standard_task_runner.py:63} INFO - Started process 1190 to run task
[2024-06-28T18:15:05.348+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T06:50:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpxdeznhbi']
[2024-06-28T18:15:05.349+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask generate_and_insert_data
[2024-06-28T18:15:05.367+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:15:05.398+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T06:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T06:50:00+00:00'
[2024-06-28T18:15:05.398+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:15:05.464+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:15:05.465+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:15:05.465+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:15:05.465+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:15:05.465+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:15:05.471+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T06:50:00+00:00, execution_date=20230101T065000, start_date=20240628T181505, end_date=20240628T181505
[2024-06-28T18:15:05.490+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:15:05.500+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:15:05.501+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:21:56.110+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:21:56.121+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-28T18:21:56.123+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-28T18:21:56.123+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:21:56.128+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 06:50:00+00:00
[2024-06-28T18:21:56.130+0000] {standard_task_runner.py:63} INFO - Started process 920 to run task
[2024-06-28T18:21:56.131+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T06:50:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpd6jyiwg6']
[2024-06-28T18:21:56.132+0000] {standard_task_runner.py:91} INFO - Job 64: Subtask generate_and_insert_data
[2024-06-28T18:21:56.148+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [running]> on host 6570e5857071
[2024-06-28T18:21:56.177+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T06:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T06:50:00+00:00'
[2024-06-28T18:21:56.178+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:21:56.234+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:21:56.235+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:21:56.235+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:21:56.235+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:21:56.235+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:21:56.240+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T06:50:00+00:00, execution_date=20230101T065000, start_date=20240628T182156, end_date=20240628T182156
[2024-06-28T18:21:56.278+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:21:56.285+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:21:56.286+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:31:54.161+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:31:54.171+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-28T18:31:54.174+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [queued]>
[2024-06-28T18:31:54.174+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:31:54.178+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 06:50:00+00:00
[2024-06-28T18:31:54.180+0000] {standard_task_runner.py:63} INFO - Started process 868 to run task
[2024-06-28T18:31:54.181+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T06:50:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpco86sset']
[2024-06-28T18:31:54.182+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask generate_and_insert_data
[2024-06-28T18:31:54.199+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T06:50:00+00:00 [running]> on host 50bf780463b8
[2024-06-28T18:31:54.228+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T06:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T06:50:00+00:00'
[2024-06-28T18:31:54.229+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:31:54.286+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:31:54.286+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:31:54.286+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:31:54.286+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:31:54.287+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:31:54.291+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T06:50:00+00:00, execution_date=20230101T065000, start_date=20240628T183154, end_date=20240628T183154
[2024-06-28T18:31:54.319+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:31:54.326+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:31:54.326+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
