[2024-06-27T22:35:24.950+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T22:35:24.963+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [queued]>
[2024-06-27T22:35:24.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [queued]>
[2024-06-27T22:35:24.967+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T22:35:24.972+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 11:50:00+00:00
[2024-06-27T22:35:24.973+0000] {standard_task_runner.py:63} INFO - Started process 1308 to run task
[2024-06-27T22:35:24.975+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T11:50:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpt7dq9x8r']
[2024-06-27T22:35:24.975+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask generate_and_insert_data
[2024-06-27T22:35:24.995+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [running]> on host 9174587f6b1d
[2024-06-27T22:35:25.024+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T11:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T11:50:00+00:00'
[2024-06-27T22:35:25.024+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T22:35:25.059+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', './generator/ecomm_generator.py']' returned non-zero exit status 2.
[2024-06-27T22:35:25.059+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-27T22:35:25.059+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T22:35:25.066+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T11:50:00+00:00, execution_date=20230101T115000, start_date=20240627T223524, end_date=20240627T223525
[2024-06-27T22:35:25.078+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-27T22:35:25.085+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T22:35:25.086+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T18:16:42.682+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T18:16:42.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [queued]>
[2024-06-28T18:16:42.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [queued]>
[2024-06-28T18:16:42.695+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-28T18:16:42.699+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 11:50:00+00:00
[2024-06-28T18:16:42.701+0000] {standard_task_runner.py:63} INFO - Started process 2030 to run task
[2024-06-28T18:16:42.702+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T11:50:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp4lvisk5m']
[2024-06-28T18:16:42.703+0000] {standard_task_runner.py:91} INFO - Job 144: Subtask generate_and_insert_data
[2024-06-28T18:16:42.719+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [running]> on host 08cefd381a1f
[2024-06-28T18:16:42.748+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T11:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T11:50:00+00:00'
[2024-06-28T18:16:42.749+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T18:16:42.806+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-28T18:16:42.806+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-28T18:16:42.806+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-28T18:16:42.806+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T18:16:42.807+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T18:16:42.811+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T11:50:00+00:00, execution_date=20230101T115000, start_date=20240628T181642, end_date=20240628T181642
[2024-06-28T18:16:42.848+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T18:16:42.855+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T18:16:42.855+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T21:38:50.371+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T21:38:50.381+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [queued]>
[2024-06-29T21:38:50.383+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [queued]>
[2024-06-29T21:38:50.383+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T21:38:50.387+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 11:50:00+00:00
[2024-06-29T21:38:50.389+0000] {standard_task_runner.py:63} INFO - Started process 1071 to run task
[2024-06-29T21:38:50.390+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T11:50:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmpenk1p67y']
[2024-06-29T21:38:50.391+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask generate_and_insert_data
[2024-06-29T21:38:50.408+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [running]> on host afcb6fbf9265
[2024-06-29T21:38:50.437+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T11:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T11:50:00+00:00'
[2024-06-29T21:38:50.437+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T21:38:50.493+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T21:38:50.493+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T21:38:50.494+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T21:38:50.494+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T21:38:50.494+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T21:38:50.499+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T11:50:00+00:00, execution_date=20230101T115000, start_date=20240629T213850, end_date=20240629T213850
[2024-06-29T21:38:50.536+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T21:38:50.543+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T21:38:50.543+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-29T22:02:38.476+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-29T22:02:38.486+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [queued]>
[2024-06-29T22:02:38.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [queued]>
[2024-06-29T22:02:38.489+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-29T22:02:38.493+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_and_insert_data> on 2023-01-01 11:50:00+00:00
[2024-06-29T22:02:38.495+0000] {standard_task_runner.py:63} INFO - Started process 1071 to run task
[2024-06-29T22:02:38.496+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ecomm_data_pipeline', 'generate_and_insert_data', 'scheduled__2023-01-01T11:50:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/ecomm_dag.py', '--cfg-path', '/tmp/tmp2yzj9hf2']
[2024-06-29T22:02:38.497+0000] {standard_task_runner.py:91} INFO - Job 73: Subtask generate_and_insert_data
[2024-06-29T22:02:38.513+0000] {task_command.py:426} INFO - Running <TaskInstance: ecomm_data_pipeline.generate_and_insert_data scheduled__2023-01-01T11:50:00+00:00 [running]> on host 799998b0d26e
[2024-06-29T22:02:38.543+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ecomm_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T11:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T11:50:00+00:00'
[2024-06-29T22:02:38.544+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-29T22:02:38.602+0000] {logging_mixin.py:188} INFO - Error in generate_and_insert_data: Command '['python3', '/opt/airflow/generator/ecomm_generator.py']' returned non-zero exit status 1.
[2024-06-29T22:02:38.603+0000] {logging_mixin.py:188} INFO - stdout: 
[2024-06-29T22:02:38.603+0000] {logging_mixin.py:188} INFO - stderr: Traceback (most recent call last):
  File "/opt/airflow/generator/ecomm_generator.py", line 4, in <module>
    from faker import Faker
ModuleNotFoundError: No module named 'faker'
[2024-06-29T22:02:38.603+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-29T22:02:38.603+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-29T22:02:38.608+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ecomm_data_pipeline, task_id=generate_and_insert_data, run_id=scheduled__2023-01-01T11:50:00+00:00, execution_date=20230101T115000, start_date=20240629T220238, end_date=20240629T220238
[2024-06-29T22:02:38.644+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-29T22:02:38.651+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-29T22:02:38.652+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
